Add babylon app registration
Cosmo-Tech/cosmotech-terraform pull request #13
Opened 2023-04-17 15:28 UTC by enocquet

2023-05-02 08:46 UTC, vcarluer requested changes
Usually we need to create Service Principal item also (azuread_service_principal in terraform), we create it for all other app registration

2023-05-02 09:21 UTC, vcarluer requested changes
error in reference

2023-05-02 09:21 UTC, vcarluer commented on azure/create-platform-prerequisites/main.tf
> +  application_id               = azuread_application.babylon[0].application_id
I have commented by error on commit but to quickly say the same thing babylon[0] should be used only if there is a "Count=..." on the app registration. Add a var to make the app registration optional or change the application_id to azuread_application.babylon.application_id.
A "terraform validate" command may see this kind of issue.

2023-05-05 13:26 UTC, enocquet commented on azure/create-platform-prerequisites/main.tf
> +  application_id               = azuread_application.babylon[0].application_id
changed

2023-05-12 14:25 UTC, vcarluer approved these changes
OK

2023-05-15 07:26 UTC, merged