Added create adx variables
Cosmo-Tech/cosmotech-terraform pull request #26
Opened 2023-08-07 08:36 UTC by johnfolly

- [x] I added create adx variables
- [x] I updated the documentation

2023-08-07 14:43 UTC, jpla-csm commented
LGTM, except for commit name, should be create adt variable instead of adx.

2023-08-07 14:48 UTC, jpla-csm approved these changes
LGTM, except for commit name, should be create adt variable instead of adx.

2023-08-08 09:51 UTC, johnfolly commented
I fixed it and changed to create adt

2023-09-07 12:57 UTC, enocquet requested changes

2023-09-07 12:57 UTC, enocquet commented on azure/new-workspace/terraform.tfvars
> +create_adt_instance = "false"
let it like : create_adt_instance = ""

2023-09-08 07:56 UTC, enocquet approved these changes

2023-09-08 07:58 UTC, merged